version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: python app.py run -h 0.0.0.0
    hostname: localhost:5432
    volumes:
      - ./:/usr/src/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.2
    hostname: db_films
    restart: always
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=hello_flask_prod
    volumes:
      - db-data-prod:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  db-data-prod: