version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: python app.py run -h 0.0.0.0
        hostname: localhost:5432
        volumes:
            - ./:/usr/src/
        ports:
            - 5000:5000
        env_file:
            - ./.env.dev
        depends_on:
            -   db
    db:
        image: postgres:13.2
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            -   ./.env.dev
volumes:
    db-data:
