version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: python app.py run -h 0.0.0.0
        volumes:
            - ./:/usr/src/
        ports:
            - 5000:5000
        env_file:
            - ./.env.dev
