"""Initial migration

Revision ID: e12da1bd7287
Revises: 
Create Date: 2021-07-14 23:01:32.519572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e12da1bd7287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('director')
    op.drop_table('film_genre')
    op.drop_table('film')
    op.drop_table('genre')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('user_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('genre',
    sa.Column('genre_id', sa.INTEGER(), server_default=sa.text("nextval('genre_genre_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('genre_id', name='genre_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('film',
    sa.Column('film_id', sa.INTEGER(), server_default=sa.text("nextval('film_film_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('release_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=2, scale=2), autoincrement=False, nullable=False),
    sa.Column('poster', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='film_user_id_fkey'),
    sa.PrimaryKeyConstraint('film_id', name='film_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('film_genre',
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.film_id'], name='film_genre_film_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], name='film_genre_genre_id_fkey'),
    sa.PrimaryKeyConstraint('film_id', 'genre_id', name='film_genre_pkey')
    )
    op.create_table('director',
    sa.Column('director_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('director_id', name='director_pkey')
    )
    # ### end Alembic commands ###
